### ISSUE TITLE
Make sure to put your javascript files into a script directory

### ISSUE THREAD

**Issue by TheByteSizeDev** [johnbehman/Daily-Journal#2]
Keep your javascript files in a `script` directory and your CSS files in a `styles` directory. Just to keep things organized.

https://github.com/johnbehman/Daily-Journal/blob/a7c094fafe6ee208556368cd6a6e90ffbc876b6e/entries.js#L1

**Comment by johnbehman** [comment]
ok thank you Sydney I will fix it.
